# Write a Python Program to Get the ASCII Value of a Character.
print()
print(ord('S'))
print(ord('A'))
print(ord('G'))
print(ord('A'))
print(ord('R'))
print()
print(ord('G'))
print(ord('O'))
print(ord('S'))
print(ord('W'))
print(ord('A'))
print(ord('M'))
print(ord('I'))
print()